version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        REACT_APP_API_URL: http://localhost:8080
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80"  # Map container's port 80 to host 3000
    networks:
      - vouchers

networks:
  vouchers:
    driver: bridge
